<?php

class CG_PWMOCController extends CG_Controller
{
    protected function _GenerateCCode($model=NULL, $processor_type='')
    {
        $code = '/*********************************************************'.PHP_EOL;
        $code .= ' * oc'.$model->type.'.c is automatically generated by pwm.exe.'.PHP_EOL;
        $code .= ' * Please do not change.'.PHP_EOL;
        $code .= ' *'.PHP_EOL;
        $code .= ' * To obtain a copy of pwm.exe go to'.PHP_EOL;
        $code .= ' * http://www.kmitechnology.com/.'.PHP_EOL;
        $code .= ' *'.PHP_EOL;
        $code .= ' *********************************************************/'.PHP_EOL;
        $code .= PHP_EOL;
        $code .= PHP_EOL;
        $code .= '#include <'.$processor_type.'.h>'.PHP_EOL;
        $code .= ''.PHP_EOL;
        $code .= ''.PHP_EOL;
        $code .= 'void oc'.$model->type.'Init(void)'.PHP_EOL;
        $code .= '{'.PHP_EOL;
        $code .= PHP_EOL;
        $code .= '    // init PWM'.PHP_EOL;
        $code .= '    // set the initial duty cycles (master and slave)'.PHP_EOL;
        $code .= '    OC'.$model->type.'R = OC'.$model->type.'RS = 200;  // init at 50%'.PHP_EOL;
        $code .= ''.PHP_EOL;
        if(!empty($model->timer))
            $code .= '    // activate the PWM module'.PHP_EOL;
        if($model->timer == 2)
        {
            if($model->single_continuous == 1)
                $code .= '    OC'.$model->type.'CON = 0x0002;'.PHP_EOL;
            elseif($model->single_continuous == 2)
                $code .= '    OC'.$model->type.'CON = 0x0006;'.PHP_EOL;
        }
        elseif($model->timer == 3)
        {
            if($model->single_continuous == 1)
                $code .= '    OC'.$model->type.'CON = 0x000A;'.PHP_EOL;
            elseif($model->single_continuous == 2)
                $code .= '    OC'.$model->type.'CON = 0x000E;'.PHP_EOL;
        }
        $code .= '} // end oc'.$model->type.'Init'.PHP_EOL;
        $code .= PHP_EOL;
        $code .= PHP_EOL;
        $code .= '/*'.PHP_EOL;
        $code .= 'main(void)'.PHP_EOL;
        $code .= '{'.PHP_EOL;
        $code .= '    pinAssign();'.PHP_EOL;
        if($model->timer == 2)
            $code .= '    timer2Init();'.PHP_EOL;
        elseif($model->timer == 3)
            $code .= '    timer3Init();'.PHP_EOL;
        $code .= '    oc'.$model->type.'Init();'.PHP_EOL;
        $code .= PHP_EOL;
        $code .= '    // main loop'.PHP_EOL;
        $code .= '    while (1)'.PHP_EOL;
        $code .= '       ;'.PHP_EOL;
        $code .= PHP_EOL;
        $code .= '} // end main'.PHP_EOL;
        $code .= '*/'.PHP_EOL;
        
        return $code;
    }
}