<?php

class CG_PWMTimerController extends CG_Controller
{
    protected function _GenerateCCode($model=NULL, $processor_type='')
    {
        $code = '/*********************************************************'.PHP_EOL;
        $code .= ' * timer'.$model->type.'.c is automatically generated by PicCodeGen.'.PHP_EOL;
        $code .= ' * Please do not change.'.PHP_EOL;
        $code .= ' *'.PHP_EOL;
        $code .= ' * To obtain a copy of PicCodeGen go to'.PHP_EOL;
        $code .= ' * http://www.kmitechnology.com/.'.PHP_EOL;
        $code .= ' *'.PHP_EOL;
        $code .= ' *********************************************************/'.PHP_EOL;
        $code .= PHP_EOL;
        $code .= PHP_EOL;
        $code .= '#include <'.$processor_type.'.h>'.PHP_EOL;
        $code .= PHP_EOL;
        $code .= PHP_EOL;
        $code .= 'void timer'.$model->type.'Init(void)'.PHP_EOL;
        $code .= '{'.PHP_EOL;
        $code .= '    // init TMR'.$model->type.' to provide the timebase'.PHP_EOL;
        switch($model->timer_prescale)
        {
            case 1:
                $code .= '    T'.$model->type.'CON = 0x8000;  // enable TMR'.$model->type.', prescale 1:1, internal clock'.PHP_EOL;
                break;
                
            case 8:
                $code .= '    T'.$model->type.'CON = 0x8010;  // enable TMR'.$model->type.', prescale 1:8, internal clock'.PHP_EOL;
                break;
                
            case 64:
                $code .= '    T'.$model->type.'CON = 0x8020;  // enable TMR'.$model->type.', prescale 1:64, internal clock'.PHP_EOL;
                break;
                
            case 256:
                $code .= '    T'.$model->type.'CON = 0x8030;  // enable TMR'.$model->type.', prescale 1:256, internal clock'.PHP_EOL;
                break;
        }
        if(!empty($model->pr_value))
            $code .= '    PR'.$model->type.' = '.$model->pr_value.';     // set the period for the given bitrate'.PHP_EOL;
        $code .= '    _T'.$model->type.'IF = 0;       // clear interrupt flag'.PHP_EOL;
        $code .= '    _T'.$model->type.'IE = 1;       // enable TMR'.$model->type.' interrupt'.PHP_EOL;
        $code .= '}'.PHP_EOL;
        $code .= PHP_EOL;
        $code .= 'void _ISRFAST _T'.$model->type.'Interrupt(void)'.PHP_EOL;
        $code .= '{'.PHP_EOL;
        $code .= '    // clear interrupt flag and exit'.PHP_EOL;
        $code .= '    _T'.$model->type.'IF = 0;'.PHP_EOL;
        $code .= '} // end of T'.$model->type.'Interrupt'.PHP_EOL;
        
        return $code;
    }
    
    protected function _GenerateHCode($model=null, $processor_type='')
    {
        $code = '/************************************************'.PHP_EOL;
        $code .= ' * Timer'.$model->type.'.h is automatically generated by PicCodeGen'.PHP_EOL;
        $code .= ' * Please do not change.'.PHP_EOL;
        $code .= ' *'.PHP_EOL;
        $code .= ' * To obtain a copy of PicCodeGen go to'.PHP_EOL;
        $code .= ' * http://www.kmitechnology.com/.'.PHP_EOL;
        $code .= ' *'.PHP_EOL;
        $code .= ' ************************************************/'.PHP_EOL;
        $code .= PHP_EOL.PHP_EOL.PHP_EOL;
        $code .= 'void timer'.$model->type.'Init(void);'.PHP_EOL;
        
        return $code;
    }
}