<?php

class CG_PinAssignmentController extends CG_Controller
{
    protected function _GenerateCCode($model=NULL, $processor_type='')
    {
        $code = PHP_EOL.'/************************************************'.PHP_EOL;
        $code .= ' * To obtain a copy of PicCodeGen go to'.PHP_EOL;
        $code .= ' * http://www.kmitechnology.com/.'.PHP_EOL;
        $code .= ' *'.PHP_EOL;
        $code .= ' ************************************************/'.PHP_EOL;
        $code .= PHP_EOL;
        $code .= PHP_EOL;
        $code .= "#include <{$processor_type}.h>".PHP_EOL;
        $code .= 'void'.PHP_EOL;
        $code .= 'pinAssign(void)'.PHP_EOL;
        $code .= '{'.PHP_EOL;
        $code .= '     //***********************************'.PHP_EOL;
        $code .= '     // Unlock Registers'.PHP_EOL;
        $code .= '     //***********************************'.PHP_EOL;
        $code .= '     asm volatile ("MOV #OSCCON, w1\\n"'.PHP_EOL;
        $code .= '         "MOV #0x46,w2\\n"'.PHP_EOL;
        $code .= '         "MOV #0x57,w3\\n"'.PHP_EOL;
        $code .= '         "MOV.b w2,[w1]\\n"'.PHP_EOL;
        $code .= '         "MOV.b w3,[w1]\\n"'.PHP_EOL;
        $code .= '         "BCLR OSCCON,#6"'.PHP_EOL;
        $code .= '     );'.PHP_EOL.PHP_EOL;
            
        foreach($model::$attributes as $key => $data)
        {
            if($key === 'input' || $key === 'output')
            {
                foreach($data as $attribute)
                {
                    if($model->$attribute !== '')
                        $code .= '     '.$model->InitializeAttributeInCode($attribute, $model->$attribute);
                }
            }
        }
            
        $code .= PHP_EOL.'     //***********************************'.PHP_EOL;
        $code .= '     // Lock Registers'.PHP_EOL;
        $code .= '     //***********************************'.PHP_EOL;
        $code .= '     asm volatile ("MOV #OSCCON, w1\\n"'.PHP_EOL;
        $code .= '         "MOV #0x46,w2\\n"'.PHP_EOL;
        $code .= '         "MOV #0x57,w3\\n"'.PHP_EOL;
        $code .= '         "MOV.b w2,[w1]\\n"'.PHP_EOL;
        $code .= '         "MOV.b w3,[w1]\\n"'.PHP_EOL;
        $code .= '         "BCLR OSCCON,#6"'.PHP_EOL;
        $code .= '     );'.PHP_EOL;
        $code .= '}// end pinAssign'.PHP_EOL;
        
        return $code;
    }
    
    protected function _GenerateHCode($model=NULL, $processor_type='')
    {
        $code = '/************************************************'.PHP_EOL;
        $code .= ' * pinAssign.h is automatically generated by PicCodeGen'.PHP_EOL;
        $code .= ' * Please do not change.'.PHP_EOL;
        $code .= ' *'.PHP_EOL;
        $code .= ' * To obtain a copy of PicCodeGen go to'.PHP_EOL;
        $code .= ' * http://www.kmitechnology.com/.'.PHP_EOL;
        $code .= ' *'.PHP_EOL;
        $code .= ' ************************************************/'.PHP_EOL;
        $code .= PHP_EOL.PHP_EOL;
        $code .= "#include <{$processor_type}.h>".PHP_EOL.PHP_EOL;
        $code .= 'void pinAssign(void);'.PHP_EOL;
        
        return $code;
    }
}