<?php

class CG_Timer1Controller extends CG_Controller
{
    protected function _GenerateCCode($model=NULL, $processor_type='')
    {
        $code = '';
        
//        if(!$model->allAttributesEmpty())
//        {
//            $code = PHP_EOL.'/************************************************'.PHP_EOL;
//            $code .= ' * To obtain a copy of PicCodeGen go to'.PHP_EOL;
//            $code .= ' * http://www.kmitechnology.com/.'.PHP_EOL;
//            $code .= ' *'.PHP_EOL;
//            $code .= ' ************************************************/'.PHP_EOL;
//            $code .= PHP_EOL;
//            $code .= PHP_EOL;
//            $code .= "#include <{$processorType}.h>".PHP_EOL;
//            $code .= PHP_EOL;
//            $code .= '#define USE_AND_OR'.PHP_EOL;
//            $code .= '#include "timer.h"'.PHP_EOL;
//            $code .= '#include "timer1.h"'.PHP_EOL;
//            $code .= PHP_EOL;
//            $code .= '#define RELOAD '.$this->reloadValue.PHP_EOL;
//            $code .= PHP_EOL;
//            $code .= 'void'.PHP_EOL;
//            $code .= 'timer1Init(void)'.PHP_EOL;
//            $code .= '{'.PHP_EOL;
//            $code .= '   //    SetPriorityIntT1(priority);'.PHP_EOL;
//            $code .= '   OpenTimer1(T1_ON | T1_GATE_OFF | T1_PS_1_256 | T1_SOURCE_INT,RELOAD);'.PHP_EOL;
//            $code .= '   T1_Clear_Intr_Status_Bit;'.PHP_EOL;
//            $code .= '   EnableIntT1;'.PHP_EOL;
//            $code .= '} // end timer1Init'.PHP_EOL;
//            $code .= PHP_EOL;
//            $code .= 'void _ISR _T1Interrupt(void)'.PHP_EOL;
//            $code .= '{'.PHP_EOL;
//            if(!empty($this->t1Includes))
//            {
//                $code .= '   // User code here'.PHP_EOL;
//                $code .= '   '.$this->t1Includes.PHP_EOL;
//            }
//            $code .= '   // End user code'.PHP_EOL;
//            $code .= '   T1_Clear_Intr_Status_Bit;'.PHP_EOL;
//            $code .= '} // end U1RXInterrupt'.PHP_EOL;
//            $code .= PHP_EOL;
//            
//            $this->writeFile($code);
//        }
        
        return $code;
    }
    
    protected function _GenerateHCode($model=NULL, $processor_type='')
    {
        $code = '/************************************************'.PHP_EOL;
        $code .= ' * Timer1.h is automatically generated by PicCodeGen'.PHP_EOL;
        $code .= ' * Please do not change.'.PHP_EOL;
        $code .= ' *'.PHP_EOL;
        $code .= ' * To obtain a copy of PicCodeGen go to'.PHP_EOL;
        $code .= ' * http://www.kmitechnology.com/.'.PHP_EOL;
        $code .= ' *'.PHP_EOL;
        $code .= ' ************************************************/'.PHP_EOL;
        $code .= PHP_EOL.PHP_EOL.PHP_EOL;
        $code .= 'void timer1Init(void);'.PHP_EOL;
        
        return $code;
    }
}