/************************************************
 * bbI2C.h is automatically generated by PicCodeGen
 * Please do not change.
 *
 * To obtain a copy of PicCodeGen go to
 * http://www.kmitechnology.com/.
 *
 ************************************************/



void i2cinit(void);
void i2cstart(void);
void i2csendbyte(unsigned char bytetosend);
unsigned char i2cgetack(void);
unsigned char i2cgetbyte(void);
void i2csendack(void);
unsigned char i2cgetack(void);
void i2cstop(void);
void i2csendnack(void);
