/*********************************************************
 * config.c is automatically generated by PicCodeGen.
 * Please do not change.
 *
 * To obtain a copy of PicCodeGen go to
 * http://www.kmitechnology.com/.
 *
 *********************************************************/

_CONFIG1(JTAGEN_ON & GCP_OFF & GWRP_OFF & BKBUG_OFF & ICS_PGx1 & FWDTEN_OFF & WINDIS_OFF & FWPSA_PR32 & WDTPS_PS1)

_CONFIG2(IESO_OFF & FNOSC_FRC & FCKSM_CSECME & OSCIOFNC_OFF & IOL1WAY_OFF & I2C1SEL_SEC & POSCMOD_EC)

