/************************************************
 * main.c is automatically generated by PicCodeGen
 * Please do not change.
 *
 * To obtain a copy of PicCodeGen go to
 * http://www.kmitechnology.com/.
 *
 ***********************************************/

#define USE_AND_OR

#include "uart.h"
#include "uart2.h"

#include <p24FJ32GA002.h>


// User code here
void before(){}

int
main(void)
{
    CLKDIV = 0;
    uart2Init(config21, config22, BRATE2);

    TRISB = 0x0;
   // User code here
   void inside(){}
}
