/*********************************************************
 * oc3.c is automatically generated by pwm.exe.
 * Please do not change.
 *
 * To obtain a copy of pwm.exe go to
 * http://www.kmitechnology.com/.
 *
 *********************************************************/


#include <p24FJ32GA002.h>


void oc3Init(void)
{

    // init PWM
    // set the initial duty cycles (master and slave)
    OC3R = OC3RS = 200;  // init at 50%

} // end oc3Init


/*
main(void)
{
    pinAssign();
    oc3Init();

    // main loop
    while (1)
       ;

} // end main
*/
