/*********************************************************
 * oc4.c is automatically generated by pwm.exe.
 * Please do not change.
 *
 * To obtain a copy of pwm.exe go to
 * http://www.kmitechnology.com/.
 *
 *********************************************************/


#include <p24FJ32GA002.h>


void oc4Init(void)
{

    // init PWM
    // set the initial duty cycles (master and slave)
    OC4R = OC4RS = 200;  // init at 50%

} // end oc4Init


/*
main(void)
{
    pinAssign();
    oc4Init();

    // main loop
    while (1)
       ;

} // end main
*/
