/************************************************
 * pinAssign.h is automatically generated by PicCodeGen
 * Please do not change.
 *
 * To obtain a copy of PicCodeGen go to
 * http://www.kmitechnology.com/.
 *
 ************************************************/


#include <p24FJ32GA002.h>

void pinAssign(void);
