/*********************************************************
 * timer3.c is automatically generated by PicCodeGen.
 * Please do not change.
 *
 * To obtain a copy of PicCodeGen go to
 * http://www.kmitechnology.com/.
 *
 *********************************************************/


#include <p24FJ32GA002.h>


void timer3Init(void)
{
    // init TMR3 to provide the timebase
    T3CON = 0x8000;  // enable TMR3, prescale 1:1, internal clock
    _T3IF = 0;       // clear interrupt flag
    _T3IE = 1;       // enable TMR3 interrupt
}

void _ISRFAST _T3Interrupt(void)
{
    // clear interrupt flag and exit
    _T3IF = 0;
} // end of T3Interrupt
