/************************************************
 * Timer2.h is automatically generated by PicCodeGen
 * Please do not change.
 *
 * To obtain a copy of PicCodeGen go to
 * http://www.kmitechnology.com/.
 *
 ************************************************/



void timer2Init(void);
