/*********************************************************
 * timer2.c is automatically generated by PicCodeGen.
 * Please do not change.
 *
 * To obtain a copy of PicCodeGen go to
 * http://www.kmitechnology.com/.
 *
 *********************************************************/


#include <p24FJ32GA002.h>


void timer2Init(void)
{
    // init TMR2 to provide the timebase
    T2CON = 0x8010;  // enable TMR2, prescale 1:8, internal clock
    PR2 = 2;     // set the period for the given bitrate
    _T2IF = 0;       // clear interrupt flag
    _T2IE = 1;       // enable TMR2 interrupt
}

void _ISRFAST _T2Interrupt(void)
{
    // clear interrupt flag and exit
    _T2IF = 0;
} // end of T2Interrupt
