/************************************************
 * uart1.h is automatically generated by theEngineerTutor.com.
 * Please do not change.
 *
 * To obtain a copy of PicCodeGen go to
 * http://www.theEngineerTutor.com/.
 *
 ************************************************/


#define BRATE  1

void uart1ps(unsigned char *st);
int uart1GetChar(void);
int uart1IsChar(void);
void uart1put(unsigned char c);
void uart1Init(unsigned int config1, unsigned int config2, unsigned int brate);

int config1 = UART_EN | UART_IDLE_CON | UART_IrDA_DISABLE | UART_MODE_FLOW | UART_UEN_01 | UART_EN_WAKE | UART_DIS_LOOPBACK | UART_EN_ABAUD | UART_NO_PAR_8BIT | UART_BRGH_SIXTEEN | UART_1STOPBIT;

int config2 = UART_TX_ENABLE;
